# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USERS:     [ROLE_USERS_MENU, ROLE_USERS_ADD, ROLE_USERS_SHOW, ROLE_USERS_EDIT, ROLE_USERS_DELETE]
        ROLE_ADMIN:       [ROLE_USER, ROLE_USERS]
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path: /
                always_use_default_target_path: true
                failure_path: fos_user_security_login
            logout:       true
            anonymous:    true
            remember_me:
                secret:     '%secret%'
                lifetime:   31536000
                path:       /

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user$, role: ROLE_USERS_MENU }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/, role: ROLE_USER }
